/* eslint-env node */
/* eslint no-console: 0 */
/* global process */
/* global __dirname */

var gulp = require('gulp');
var gutil = require('gulp-util');
var bower = require('bower');
var _ = require('lodash');
// var concat = require('gulp-concat');
var sass = require('gulp-sass');
var minifyCss = require('gulp-minify-css');
var rename = require('gulp-rename');
var sh = require('shelljs');
var karma = require('karma').server;
var plugin = require('gulp-cordova-plugin');
var eslint = require('gulp-eslint');
var packageJSON = require('./package.json');
var protractor = require('gulp-protractor').protractor;
var webdriverUpdate = require('gulp-protractor').webdriver_update;
var webdriverStandalone = require('gulp-protractor').webdriver_standalone;
var nunjucksRender = require('gulp-nunjucks-render');

var argv = require('yargs').argv;

var assets = require('./config/assets/default');

var isDevice = false;

var paths = {
    sass: ['scss/styles.scss', 'scss/**/*.scss'],
    template: ['config/**/*'],
    css: 'www/assets/css'
};

gulp.task('default', ['setupEnv', 'template', 'sass', 'lint']);

gulp.task('setupEnv', function(done) {
    process.env.NODE_ENV = argv.env || 'dev';
    isDevice = !!argv.device;

    console.log('Running Gulp with Environment SETUP: ', process.env);
    console.log('Running Gulp with ARGS: ', argv);

    done();
});

gulp.task('sass', function(done) {
    gulp.src('./scss/styles.scss')
        .pipe(sass({
            errLogToConsole: true
        }))
        .pipe(gulp.dest(paths.css))
        .pipe(minifyCss({
            keepSpecialComments: 0
        }))
        .pipe(rename({ extname: '.min.css' }))
        .pipe(gulp.dest(paths.css))
        .on('end', done);
});

gulp.task('template', ['setupEnv'], function() {

    console.log('PROCESS: ', process.env.NODE_ENV)
    console.log('DEVICE: ', isDevice);

    if (isDevice) {
        console.log('Removing ngCordova Mocks');
        _.remove(assets.mobile.lib.js, function(lib) { return /ng-cordova-mocks.js$/i.test(lib); });
    }
    else {
        console.log('Removing ngCordova');
        _.remove(assets.mobile.lib.js, function(lib) { return /ng-cordova.js$/i.test(lib); });
    }

    console.log('Templating assets: ' + assets.mobile.lib.js);

    return gulp.src('config/templates/*.html')
        .pipe(nunjucksRender({
            path: 'config',
            ext: '.html',
            data: {
                editWarning: 'Do not edit this file directly - it will be overwritten. Instead make changes to /config/templatess/index.template.html',
                jsLibs: assets.mobile.lib.js,
                jsFiles: assets.mobile.js,
                cssFiles: assets.mobile.css,
                fontFiles: assets.mobile.fonts
            }
        }))
        .pipe(rename('index.html'))
        .pipe(gulp.dest('www/'));
});

gulp.task('lint', function() {
    // ESLint ignores files with "node_modules" paths.
    // So, it's best to have gulp ignore the directory as well.
    // Also, Be sure to return the stream from the task;
    // Otherwise, the task may end before the stream has finished.
    return gulp.src(['www/modules/**/*.js', '!node_modules/**'])
        // eslint() attaches the lint output to the "eslint" property
        // of the file object so it can be used by other modules.
        .pipe(eslint())
        // eslint.format() outputs the lint results to the console.
        // Alternatively use eslint.formatEach() (see Docs).
        .pipe(eslint.format())
        // To have the process exit with an error code (1) on
        // lint error, return the stream and pipe to failAfterError last.
        .pipe(eslint.failAfterError());
});

gulp.task('watch', function() {
    gulp.watch(paths.sass, ['sass']);
    gulp.watch(paths.template, ['template']);
});

gulp.task('install', ['git-check'], function() {
    return bower.commands.install()
        .on('log', function(data) {
            gutil.log('bower', gutil.colors.cyan(data.id), data.message);
        });
});

gulp.task('git-check', function(done) {
    if (!sh.which('git')) {
        console.log(
            '  ' + gutil.colors.red('Git is not installed.'),
            '\n  Git, the version control system, is required to download Ionic.',
            '\n  Download git here:', gutil.colors.cyan('http://git-scm.com/downloads') + '.',
            '\n  Once git is installed, run \'' + gutil.colors.cyan('gulp install') + '\' again.'
        );
        process.exit(1);
    }
    done();
});


gulp.task('webdriver_update', webdriverUpdate);
gulp.task('webdriver_standalone', webdriverStandalone);

gulp.task('test', ['webdriver_update'], function(done) {
    gulp.src([]).pipe(protractor({
        configFile: 'protractor.conf.js'
    })).on('error', function(e) {
        console.log(e);
    }).on('end', done);
});


gulp.task('plugins', function() {
    var plugins = packageJSON.cordovaPlugins;
    return gulp.src('./plugins')
        .pipe(plugin(plugins));
});
